### ISSUE TITLE
NoMethodError: undefined method `new' for Sidekiq:Module

### ISSUE THREAD

**Issue by fredkelly** [getvero/vero#53]
I've configured `config.async = :sidekiq` but get the following error when trying to call `Vero::Trackable#track!`:

```ruby
NoMethodError: undefined method `new' for Sidekiq:Module`
```

Is there an update to sidekiq that needs to be reflected in this gem perhaps?

**Comment by jylamont** [comment]
Hey @fredkelly, what version of the Vero gem are you using? I believe this error shows unless you're on 0.9.0. Let me know if its still an issue.

**Comment by fredkelly** [comment]
Thanks James, looks like I'd fallen foul of a Gemfile incompatibility and ended up on an older version!

**Comment by jylamont** [comment]
Glad to hear its sorted now :)
